version: '3.8'
services:
  3d_gen_4_print:
    container_name: 3D_Gen_4_Print_Container
    build: .  # This line tells Docker Compose to build an image from the Dockerfile in the current directory
    ports:
      - "7890:7860"
    volumes:
      - pytorch_vol:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]

volumes:
  pytorch_vol: